<a href="https://colab.research.google.com/github/hamdikhasawneh/AI-sepsis/blob/main/notebooks/01_data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Mount Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from pathlib import Path

DATA_DIR = Path('/content/drive/MyDrive/gp/Cleaned')
print(DATA_DIR.exists())

True

In [ ]:
import zipfile

zip_path = "/content/drive/MyDrive/gp/Cleaned/chartevents_labevents.zip"

with zipfile.ZipFile(zip_path, 'r') as z:
    print(z.namelist())

['Cleaned/', 'Cleaned/chartevents.csv', 'Cleaned/labevents.csv']

In [ ]:
for file in DATA_DIR.iterdir():
    print(file.name)

inputevents.csv
outputevents.csv
procedureevents.csv
ingredientevents.csv
datetimeevents.csv
icustays.csv
d_items.csv
patients.csv
prescriptions.csv
admissions.csv
microbiologyevents.csv
caregiver.csv
diagnoses_icd.csv
d_labitems.csv
chartevents_labevents.zip

##Load base tables

In [ ]:
import pandas as pd

In [ ]:
patients = pd.read_csv(DATA_DIR / 'patients.csv')
admissions = pd.read_csv(DATA_DIR / 'admissions.csv')
icustays = pd.read_csv(DATA_DIR / 'icustays.csv')

## Inspect Tables

In this section, we check:
- shape
- columns
- sample rows

In [ ]:
print("patients:", patients.shape)
print("admissions:", admissions.shape)
print("icustays:", icustays.shape)

patients: (364627, 6)
admissions: (546028, 16)
icustays: (94458, 8)

In [ ]:
print("patients columns:")
print(patients.columns.tolist())
print("\nadmissions columns:")
print(admissions.columns.tolist())
print("\nicustays columns:")
print(icustays.columns.tolist())

patients columns:
['subject_id', 'gender', 'anchor_age', 'anchor_year', 'anchor_year_group', 'dod']

admissions columns:
['subject_id', 'hadm_id', 'admittime', 'dischtime', 'deathtime', 'admission_type', 'admit_provider_id', 'admission_location', 'discharge_location', 'insurance', 'language', 'marital_status', 'race', 'edregtime', 'edouttime', 'hospital_expire_flag']

icustays columns:
['subject_id', 'hadm_id', 'stay_id', 'first_careunit', 'last_careunit', 'intime', 'outtime', 'los']

In [ ]:
patients.head()

   subject_id gender  anchor_age  anchor_year anchor_year_group         dod
0    10000032      F          52         2180       2014 - 2016  2180-09-09
1    10000048      F          23         2126       2008 - 2010         NaN
2    10000058      F          33         2168       2020 - 2022         NaN
3    10000068      F          19         2160       2008 - 2010         NaN
4    10000084      M          72         2160       2017 - 2019  2161-02-13

In [ ]:
admissions.head(10)
admissions[admissions.subject_id == 10000032]

,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admit_provider_id,admission_location,discharge_location,insurance,language,marital_status,race,edregtime,edouttime,hospital_expire_flag
0,10000032,22595853,2180-05-06 22:23:00,2180-05-07 17:15:00,NaN,URGENT,P49AFC,TRANSFER FROM HOSPITAL,HOME,Medicaid,English,WIDOWED,WHITE,2180-05-06 19:17:00,2180-05-06 23:30:00,0
1,10000032,22841357,2180-06-26 18:27:00,2180-06-27 18:49:00,NaN,EW EMER.,P784FA,EMERGENCY ROOM,HOME,Medicaid,English,WIDOWED,WHITE,2180-06-26 15:54:00,2180-06-26 21:31:00,0
2,10000032,25742920,2180-08-05 23:44:00,2180-08-07 17:50:00,NaN,EW EMER.,P19UTS,EMERGENCY ROOM,HOSPICE,Medicaid,English,WIDOWED,WHITE,2180-08-05 20:58:00,2180-08-06 01:44:00,0
3,10000032,29079034,2180-07-23 12:35:00,2180-07-25 17:55:00,NaN,EW EMER.,P06OTX,EMERGENCY ROOM,HOME,Medicaid,English,WIDOWED,WHITE,2180-07-23 05:54:00,2180-07-23 14:00:00,0

In [ ]:
icustays.head()

,subject_id,hadm_id,stay_id,first_careunit,last_careunit,intime,outtime,los
0,10000032,29079034,39553978,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2180-07-23 14:00:00,2180-07-23 23:50:47,0.410266
1,10000690,25860671,37081114,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2150-11-02 19:37:00,2150-11-06 17:03:17,3.893252
2,10000980,26913865,39765666,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2189-06-27 08:42:00,2189-06-27 20:38:27,0.497535
3,10001217,24597018,37067082,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),2157-11-20 19:18:02,2157-11-21 22:08:00,1.118032
4,10001217,27703517,34592300,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),2157-12-19 15:42:24,2157-12-20 14:27:41,0.948113

## Creating Cohort

In [ ]:
cohort = icustays.merge(
    admissions,
    on=['subject_id', 'hadm_id'],
    how='left'
).merge(
    patients,
    on='subject_id',
    how='left'
)
cohort.head()
print("cohort shape:", cohort.shape)

cohort shape: (94458, 27)

In [ ]:
cohort.isnull().sum().sort_values(ascending=False).head(20)

deathtime             83117
dod                   56491
edregtime             32331
edouttime             32331
marital_status         7761
insurance              1523
discharge_location      848
language                396
outtime                  14
los                      14
admit_provider_id         2
dischtime                 0
admittime                 0
last_careunit             0
intime                    0
first_careunit            0
subject_id                0
hadm_id                   0
stay_id                   0
race                      0
dtype: int64

In [ ]:
print("Duplicate rows:", cohort.duplicated().sum())

Duplicate rows: 0

### Saving Cohort

In [ ]:
output_dir = Path('/content/drive/MyDrive/mimic_iv_processed')
output_dir.mkdir(parents=True, exist_ok=True)

cohort.to_csv(output_dir / 'icu_cohort.csv', index=False)
print("Saved successfully")

Saved successfully

In [ ]:
print("Cohort shape:", cohort.shape)
print(cohort["stay_id"].nunique())
print(cohort.shape[0])
print(cohort.duplicated(subset="stay_id").sum())

Cohort shape: (94458, 27)
94458
94458
0

In [ ]:
cohort.columns

Index(['subject_id', 'hadm_id', 'stay_id', 'first_careunit', 'last_careunit',
       'intime', 'outtime', 'los', 'admittime', 'dischtime', 'deathtime',
       'admission_type', 'admit_provider_id', 'admission_location',
       'discharge_location', 'insurance', 'language', 'marital_status', 'race',
       'edregtime', 'edouttime', 'hospital_expire_flag', 'gender',
       'anchor_age', 'anchor_year', 'anchor_year_group', 'dod'],
      dtype='object')

### Converting Data-Time

In [ ]:
cohort["intime"] = pd.to_datetime(cohort["intime"])
cohort["outtime"] = pd.to_datetime(cohort["outtime"])
cohort["admittime"] = pd.to_datetime(cohort["admittime"])
cohort["dischtime"] = pd.to_datetime(cohort["dischtime"])

### Calculating Length of ICU stay in column icu_los_hours

In [ ]:
cohort["icu_los_hours"] = (cohort["outtime"] - cohort["intime"]).dt.total_seconds() / 3600
cohort["icu_los_hours"].describe()

count    94444.000000
mean        87.120596
std        129.659365
min          0.030000
25%         26.309097
50%         47.175556
75%         92.701806
max       5433.673889
Name: icu_los_hours, dtype: float64

### Filtering Short ICU stays

In [ ]:
# Removing less than 4 hours
cohort = cohort[cohort["icu_los_hours"] >= 4]
cohort.shape

(93730, 28)

In [ ]:
cohort.to_csv(output_dir / "icu_cohort.csv", index=False)
print("Clean cohort saved")

Clean cohort saved

In [ ]:
cohort["anchor_age"].describe()

count    93730.000000
mean        63.045610
std         16.712152
min         18.000000
25%         53.000000
50%         65.000000
75%         76.000000
max         91.000000
Name: anchor_age, dtype: float64

In [ ]:
# Filtering adult patients
cohort = cohort[cohort["anchor_age"] >= 18]
print(cohort.shape)

(93730, 28)

In [ ]:
output_dir = Path('/content/drive/MyDrive/mimic_iv_processed')
output_dir.mkdir(parents=True, exist_ok=True)

cohort.to_csv(output_dir / "icu_cohort.csv", index=False)

print("Clean ICU cohort saved")

## Identify Vital Sign ITEMIDs

In [ ]:
d_items = pd.read_csv(DATA_DIR / "d_items.csv")
print(d_items.shape)
print(d_items.columns)

(4095, 9)
Index(['itemid', 'label', 'abbreviation', 'linksto', 'category', 'unitname',
       'param_type', 'lownormalvalue', 'highnormalvalue'],
      dtype='object')

In [ ]:
# Important Vital Signs
# Heart Rate
d_items[d_items["label"].str.contains("Heart Rate", case=False, na=False)]

,itemid,label,abbreviation,linksto,category,unitname,param_type,lownormalvalue,highnormalvalue
2,220045,Heart Rate,HR,chartevents,Routine Vital Signs,bpm,Numeric,NaN,NaN
3,220046,Heart rate Alarm - High,HR Alarm - High,chartevents,Alarms,bpm,Numeric,NaN,NaN
4,220047,Heart Rate Alarm - Low,HR Alarm - Low,chartevents,Alarms,bpm,Numeric,NaN,NaN

In [ ]:
# Respiratory Rate
d_items[d_items["label"].str.contains("Respiratory", case=False, na=False)]

,itemid,label,abbreviation,linksto,category,unitname,param_type,lownormalvalue,highnormalvalue
28,220210,Respiratory Rate,RR,chartevents,Respiratory,insp/min,Numeric,NaN,NaN
470,223985,Respiratory Pattern,Respiratory Pattern,chartevents,Pulmonary,NaN,Text,NaN,NaN
475,223990,Respiratory Effort,Respiratory Effort,chartevents,Pulmonary,NaN,Text,NaN,NaN
799,224688,Respiratory Rate (Set),Respiratory Rate (Set),chartevents,Respiratory,insp/min,Numeric,NaN,NaN
800,224689,Respiratory Rate (spontaneous),Respiratory Rate (spontaneous),chartevents,Respiratory,insp/min,Numeric,NaN,NaN
801,224690,Respiratory Rate (Total),Respiratory Rate (Total),chartevents,Respiratory,insp/min,Numeric,NaN,36.0
839,224745,Respiratory Quotient,RQ,chartevents,Respiratory,NaN,Numeric,NaN,NaN
1327,225475,Respiratory Arrest,Respiratory Arrest,procedureevents,3-Significant Events,NaN,Processes,NaN,NaN
2075,227032,Non-Operative Respiratory (RESPIRAT),Respiratory Non-Operative,chartevents,Scores - APACHE IV,NaN,Text,NaN,NaN
2090,227047,Post-Operative Respiratory (RESPIRAT),Respiratory Post-Operative,chartevents,Scores - APACHE IV,NaN,Text,NaN,NaN
3120,228709,Respiratory,Respiratory,chartevents,MD Progress Note,NaN,Text,NaN,NaN
3281,228902,Altered Respiratory Status NCP - Expected outc...,ARS NCP - Expected outcomes,chartevents,Care Plans,NaN,Text,NaN,NaN
3282,228903,Altered Respiratory Status NCP - Goal,ARS NCP - Goal,chartevents,Care Plans,NaN,Text,NaN,NaN
3283,228905,Altered Respiratory Status NCP - Interventions,ARS NCP - Interventions,chartevents,Care Plans,NaN,Text,NaN,NaN
3284,228907,Altered Respiratory Status NCP - outcomes met,ARS NCP - outcomes met,chartevents,Care Plans,NaN,Text,NaN,NaN
3384,229090,Altered Respiratory Status NCP - Plan revised,ARS NCP - Plan revised,chartevents,Care Plans,NaN,Text,NaN,NaN
3385,229091,Altered Respiratory Status NCP - Problem resolved,ARS NCP - Problem resolved,chartevents,Care Plans,NaN,Text,NaN,NaN
3604,229425,ROS-Respiratory,ROS-Respiratory,chartevents,MD Progress Note,NaN,Text,NaN,NaN
3696,229563,Plan-Respiratory,Plan-Respiratory,chartevents,MD Progress Note,NaN,Text,NaN,NaN
4022,230094,Respiratory,Respiratory,chartevents,MD Progress Note,NaN,Text,NaN,NaN

In [ ]:
# Temperature
d_items[d_items["label"].str.contains("Temperature", case=False, na=False)]

,itemid,label,abbreviation,linksto,category,unitname,param_type,lownormalvalue,highnormalvalue
337,223761,Temperature Fahrenheit,Temperature F,chartevents,Routine Vital Signs,°F,Numeric,NaN,NaN
338,223762,Temperature Celsius,Temperature C,chartevents,Routine Vital Signs,°C,Numeric,NaN,NaN
505,224027,Skin Temperature,Skin Temp,chartevents,Skin - Assessment,NaN,Text,NaN,NaN
767,224642,Temperature Site,Temp Site,chartevents,Routine Vital Signs,NaN,Text,NaN,NaN
790,224674,Changes in Temperature,Changes in Temperature,chartevents,Toxicology,NaN,Text,NaN,NaN
1814,226329,Blood Temperature CCO (C),Blood Temp CCO (C),chartevents,Routine Vital Signs,°C,Numeric,NaN,NaN
2097,227054,TemperatureF_ApacheIV,TemperatureF_ApacheIV,chartevents,Scores - APACHE IV (2),°F,Numeric,NaN,NaN
2776,228242,Pt. Temperature (BG) (SOFT),Pt. Temperature (BG) (SOFT),chartevents,Labs,NaN,Numeric,NaN,NaN
3466,229236,Cerebral Temperature (C),Cerebral T (C),chartevents,Hemodynamics,°C,Numeric,NaN,NaN

In [ ]:
# SpO2
d_items[d_items["label"].str.contains("SpO2", case=False, na=False)]

,itemid,label,abbreviation,linksto,category,unitname,param_type,lownormalvalue,highnormalvalue
1810,226253,SpO2 Desat Limit,SpO2 Desat Limit,chartevents,Alarms,%,Numeric,NaN,NaN
3920,229862,Forehead SpO2 Sensor in Place,Forehead SpO2 Sensor in Place,chartevents,Routine Vital Signs,NaN,Checkbox,NaN,NaN

In [ ]:
# Blood Pressure
d_items[d_items["label"].str.contains("Pressure", case=False, na=False)]

,itemid,label,abbreviation,linksto,category,unitname,param_type,lownormalvalue,highnormalvalue
6,220050,Arterial Blood Pressure systolic,ABPs,chartevents,Routine Vital Signs,mmHg,Numeric,90.0,140.0
7,220051,Arterial Blood Pressure diastolic,ABPd,chartevents,Routine Vital Signs,mmHg,Numeric,60.0,90.0
8,220052,Arterial Blood Pressure mean,ABPm,chartevents,Routine Vital Signs,mmHg,Numeric,NaN,NaN
9,220056,Arterial Blood Pressure Alarm - Low,ABP Alarm - Low,chartevents,Alarms,mmHg,Numeric,NaN,NaN
10,220058,Arterial Blood Pressure Alarm - High,ABP Alarm - High,chartevents,Alarms,mmHg,Numeric,NaN,NaN
...,...,...,...,...,...,...,...,...,...
3947,229892,Pressure Ulcer #9- Date Indentified,Pressure Ulcer #9- Date Indentified,datetimeevents,Skin - Impairment,NaN,Date and time,NaN,NaN
3948,229893,Pressure Ulcer #10- Date Indentified,Pressure Ulcer #10- Date Indentified,datetimeevents,Skin - Impairment,NaN,Date and time,NaN,NaN
3954,229899,Left Ventricular Pressure Signal - Systolic,Left Ventricular Pressure Signal - Systolic,chartevents,Impella,mmHg,Numeric,NaN,NaN
3955,229900,Left Ventricular Pressure Signal - Diastolic,Left Ventricular Pressure Signal - Diastolic,chartevents,Impella,mmHg,Numeric,NaN,NaN
4036,230112,Esophageal Balloon Pressure (MT),Esophageal Balloon Pressure (MT),chartevents,GI/GU,mmHg,Numeric,NaN,NaN

In [ ]:
d_items[d_items["label"].str.contains("saturation", case=False, na=False)]

,itemid,label,abbreviation,linksto,category,unitname,param_type,lownormalvalue,highnormalvalue
31,220227,Arterial O2 Saturation,SaO2,chartevents,Labs,%,Numeric,NaN,NaN
36,220277,O2 saturation pulseoxymetry,SpO2,chartevents,Respiratory,%,Numeric,NaN,NaN
345,223769,O2 Saturation Pulseoxymetry Alarm - High,SpO2 Alarm - High,chartevents,Alarms,%,Numeric,NaN,NaN
346,223770,O2 Saturation Pulseoxymetry Alarm - Low,SpO2 Alarm - Low,chartevents,Alarms,%,Numeric,NaN,NaN
2004,226860,RA %O2 Saturation (PA Line),RA %O2 Saturation (PA Line),chartevents,PA Line Insertion,%,Numeric,NaN,NaN
2005,226861,ART %O2 saturation (PA Line),ART %O2 saturation (PA Line),chartevents,PA Line Insertion,%,Numeric,NaN,NaN
2006,226862,PA %O2 Saturation (PA Line),PA %O2 Saturation (PA Line),chartevents,PA Line Insertion,%,Numeric,NaN,NaN
2007,226863,PVR %O2 Saturation (PA Line),PVR %O2 Saturation (PA Line),chartevents,PA Line Insertion,dynes*sec/cm5,Numeric,NaN,NaN
2008,226865,SVR %O2 Saturation (PA Line),SVR %O2 Saturation (PA Line),chartevents,PA Line Insertion,dynes*sec/cm5,Numeric,NaN,NaN
2769,228232,PAR-Oxygen saturation,PAR-Oxygen saturation,chartevents,Routine Vital Signs,NaN,Text,NaN,NaN

In [ ]:
# Selected vital sign ITEMIDs

HEART_RATE_ID = 220045
RESP_RATE_ID = 220210
TEMP_C_ID = 223762
SPO2_ID = 220277
ABP_SYS_ID = 220050
ABP_DIA_ID = 220051
ABP_MEAN_ID = 220052
VITAL_ITEMIDS = [
    HEART_RATE_ID,
    RESP_RATE_ID,
    TEMP_C_ID,
    SPO2_ID,
    ABP_SYS_ID,
    ABP_DIA_ID,
    ABP_MEAN_ID
]
print(VITAL_ITEMIDS)

[220045, 220210, 223762, 220277, 220050, 220051, 220052]

## Extract Vital Signs from chartevents

In [ ]:
chartevents_zip_path = DATA_DIR / "chartevents_labevents.zip"
print(chartevents_zip_path.exists())

True

In [ ]:
import zipfile

with zipfile.ZipFile(chartevents_zip_path, 'r') as z:
    print(z.namelist())

['Cleaned/', 'Cleaned/chartevents.csv', 'Cleaned/labevents.csv']

In [ ]:
import zipfile
import pandas as pd

chartevents_zip_path = DATA_DIR / "chartevents_labevents.zip"

filtered_chunks = []
chunk_size = 500000

with zipfile.ZipFile(chartevents_zip_path, "r") as z:
    with z.open("Cleaned/chartevents.csv") as f:
        for i, chunk in enumerate(pd.read_csv(f, chunksize=chunk_size)):
            chunk = chunk[
                (chunk["stay_id"].isin(stay_ids)) &
                (chunk["itemid"].isin(VITAL_ITEMIDS))
            ]

            if not chunk.empty:
                filtered_chunks.append(chunk)

            print(f"Finished chunk {i+1}")

Finished chunk 1
Finished chunk 2
Finished chunk 3
Finished chunk 4
Finished chunk 5
Finished chunk 6
Finished chunk 7
Finished chunk 8
Finished chunk 9
Finished chunk 10
Finished chunk 11
Finished chunk 12
Finished chunk 13
Finished chunk 14
Finished chunk 15
Finished chunk 16
Finished chunk 17
Finished chunk 18
Finished chunk 19
Finished chunk 20
Finished chunk 21
Finished chunk 22
Finished chunk 23
Finished chunk 24
Finished chunk 25
Finished chunk 26
Finished chunk 27
Finished chunk 28
Finished chunk 29
Finished chunk 30
Finished chunk 31
Finished chunk 32
Finished chunk 33
Finished chunk 34
Finished chunk 35
Finished chunk 36
Finished chunk 37
Finished chunk 38
Finished chunk 39
Finished chunk 40
Finished chunk 41
Finished chunk 42
Finished chunk 43
Finished chunk 44
Finished chunk 45
Finished chunk 46
Finished chunk 47
Finished chunk 48
Finished chunk 49
Finished chunk 50
Finished chunk 51
Finished chunk 52
Finished chunk 53
Finished chunk 54
Finished chunk 55
Finished chunk 56
Finished chunk 57
Finished chunk 58
Finished chunk 59
Finished chunk 60
Finished chunk 61
Finished chunk 62
Finished chunk 63
Finished chunk 64
Finished chunk 65
Finished chunk 66
Finished chunk 67
Finished chunk 68
Finished chunk 69
Finished chunk 70
Finished chunk 71
Finished chunk 72
Finished chunk 73
Finished chunk 74
Finished chunk 75
Finished chunk 76
Finished chunk 77
Finished chunk 78
Finished chunk 79
Finished chunk 80
Finished chunk 81
Finished chunk 82
Finished chunk 83
Finished chunk 84
Finished chunk 85
Finished chunk 86
Finished chunk 87
Finished chunk 88
Finished chunk 89
Finished chunk 90
Finished chunk 91
Finished chunk 92
Finished chunk 93
Finished chunk 94
Finished chunk 95
Finished chunk 96
Finished chunk 97
Finished chunk 98
Finished chunk 99
Finished chunk 100
Finished chunk 101
Finished chunk 102
Finished chunk 103
Finished chunk 104
Finished chunk 105
Finished chunk 106
Finished chunk 107
Finished chunk 108
Finished chunk 109
Finished chunk 110
Finished chunk 111
Finished chunk 112
Finished chunk 113
Finished chunk 114
Finished chunk 115
Finished chunk 116
Finished chunk 117
Finished chunk 118
Finished chunk 119
Finished chunk 120
Finished chunk 121
Finished chunk 122
Finished chunk 123
Finished chunk 124
Finished chunk 125
Finished chunk 126
Finished chunk 127
Finished chunk 128
Finished chunk 129
Finished chunk 130
Finished chunk 131
Finished chunk 132
Finished chunk 133
Finished chunk 134
Finished chunk 135
Finished chunk 136
Finished chunk 137
Finished chunk 138
Finished chunk 139
Finished chunk 140
Finished chunk 141
Finished chunk 142
Finished chunk 143
Finished chunk 144
Finished chunk 145
Finished chunk 146
Finished chunk 147
Finished chunk 148
Finished chunk 149
Finished chunk 150
Finished chunk 151
Finished chunk 152
Finished chunk 153
Finished chunk 154
Finished chunk 155
Finished chunk 156
Finished chunk 157
Finished chunk 158
Finished chunk 159
Finished chunk 160
Finished chunk 161
Finished chunk 162
Finished chunk 163
Finished chunk 164
Finished chunk 165
Finished chunk 166
Finished chunk 167
Finished chunk 168
Finished chunk 169
Finished chunk 170
Finished chunk 171
Finished chunk 172
Finished chunk 173
Finished chunk 174
Finished chunk 175
Finished chunk 176
Finished chunk 177
Finished chunk 178
Finished chunk 179
Finished chunk 180
Finished chunk 181
Finished chunk 182
Finished chunk 183
Finished chunk 184
Finished chunk 185
Finished chunk 186
Finished chunk 187
Finished chunk 188
Finished chunk 189
Finished chunk 190
Finished chunk 191
Finished chunk 192
Finished chunk 193
Finished chunk 194
Finished chunk 195
Finished chunk 196
Finished chunk 197
Finished chunk 198
Finished chunk 199
Finished chunk 200
Finished chunk 201
Finished chunk 202
Finished chunk 203
Finished chunk 204
Finished chunk 205
Finished chunk 206
Finished chunk 207
Finished chunk 208
Finished chunk 209
Finished chunk 210
Finished chunk 211
Finished chunk 212
Finished chunk 213
Finished chunk 214
Finished chunk 215
Finished chunk 216
Finished chunk 217
Finished chunk 218
Finished chunk 219
Finished chunk 220
Finished chunk 221
Finished chunk 222
Finished chunk 223
Finished chunk 224
Finished chunk 225
Finished chunk 226
Finished chunk 227
Finished chunk 228
Finished chunk 229
Finished chunk 230
Finished chunk 231
Finished chunk 232
Finished chunk 233
Finished chunk 234
Finished chunk 235
Finished chunk 236
Finished chunk 237
Finished chunk 238
Finished chunk 239
Finished chunk 240
Finished chunk 241
Finished chunk 242
Finished chunk 243
Finished chunk 244
Finished chunk 245
Finished chunk 246
Finished chunk 247
Finished chunk 248
Finished chunk 249
Finished chunk 250
Finished chunk 251
Finished chunk 252
Finished chunk 253
Finished chunk 254
Finished chunk 255
Finished chunk 256
Finished chunk 257
Finished chunk 258
Finished chunk 259
Finished chunk 260
Finished chunk 261
Finished chunk 262
Finished chunk 263
Finished chunk 264
Finished chunk 265
Finished chunk 266
Finished chunk 267
Finished chunk 268
Finished chunk 269
Finished chunk 270
Finished chunk 271
Finished chunk 272
Finished chunk 273
Finished chunk 274
Finished chunk 275
Finished chunk 276
Finished chunk 277
Finished chunk 278
Finished chunk 279
Finished chunk 280
Finished chunk 281
Finished chunk 282
Finished chunk 283
Finished chunk 284
Finished chunk 285
Finished chunk 286
Finished chunk 287
Finished chunk 288
Finished chunk 289
Finished chunk 290
Finished chunk 291
Finished chunk 292
Finished chunk 293
Finished chunk 294
Finished chunk 295
Finished chunk 296
Finished chunk 297
Finished chunk 298
Finished chunk 299
Finished chunk 300
Finished chunk 301
Finished chunk 302
Finished chunk 303
Finished chunk 304
Finished chunk 305
Finished chunk 306
Finished chunk 307
Finished chunk 308
Finished chunk 309
Finished chunk 310
Finished chunk 311
Finished chunk 312
Finished chunk 313
Finished chunk 314
Finished chunk 315
Finished chunk 316
Finished chunk 317
Finished chunk 318
Finished chunk 319
Finished chunk 320
Finished chunk 321
Finished chunk 322
Finished chunk 323
Finished chunk 324
Finished chunk 325
Finished chunk 326
Finished chunk 327
Finished chunk 328
Finished chunk 329
Finished chunk 330
Finished chunk 331
Finished chunk 332
Finished chunk 333
Finished chunk 334
Finished chunk 335
Finished chunk 336
Finished chunk 337
Finished chunk 338
Finished chunk 339
Finished chunk 340
Finished chunk 341
Finished chunk 342
Finished chunk 343
Finished chunk 344
Finished chunk 345
Finished chunk 346
Finished chunk 347
Finished chunk 348
Finished chunk 349
Finished chunk 350
Finished chunk 351
Finished chunk 352
Finished chunk 353
Finished chunk 354
Finished chunk 355
Finished chunk 356
Finished chunk 357
Finished chunk 358
Finished chunk 359
Finished chunk 360
Finished chunk 361
Finished chunk 362
Finished chunk 363
Finished chunk 364
Finished chunk 365
Finished chunk 366
Finished chunk 367
Finished chunk 368
Finished chunk 369
Finished chunk 370
Finished chunk 371
Finished chunk 372
Finished chunk 373
Finished chunk 374
Finished chunk 375
Finished chunk 376
Finished chunk 377
Finished chunk 378
Finished chunk 379
Finished chunk 380
Finished chunk 381
Finished chunk 382
Finished chunk 383
Finished chunk 384
Finished chunk 385
Finished chunk 386
Finished chunk 387
Finished chunk 388
Finished chunk 389
Finished chunk 390
Finished chunk 391
Finished chunk 392
Finished chunk 393
Finished chunk 394
Finished chunk 395
Finished chunk 396
Finished chunk 397
Finished chunk 398
Finished chunk 399
Finished chunk 400
Finished chunk 401
Finished chunk 402
Finished chunk 403
Finished chunk 404
Finished chunk 405
Finished chunk 406
Finished chunk 407
Finished chunk 408
Finished chunk 409
Finished chunk 410
Finished chunk 411
Finished chunk 412
Finished chunk 413
Finished chunk 414
Finished chunk 415
Finished chunk 416
Finished chunk 417
Finished chunk 418
Finished chunk 419
Finished chunk 420
Finished chunk 421
Finished chunk 422
Finished chunk 423
Finished chunk 424
Finished chunk 425
Finished chunk 426
Finished chunk 427
Finished chunk 428
Finished chunk 429
Finished chunk 430
Finished chunk 431
Finished chunk 432
Finished chunk 433
Finished chunk 434
Finished chunk 435
Finished chunk 436
Finished chunk 437
Finished chunk 438
Finished chunk 439
Finished chunk 440
Finished chunk 441
Finished chunk 442
Finished chunk 443
Finished chunk 444
Finished chunk 445
Finished chunk 446
Finished chunk 447
Finished chunk 448
Finished chunk 449
Finished chunk 450
Finished chunk 451
Finished chunk 452
Finished chunk 453
Finished chunk 454
Finished chunk 455
Finished chunk 456
Finished chunk 457
Finished chunk 458
Finished chunk 459
Finished chunk 460
Finished chunk 461
Finished chunk 462
Finished chunk 463
Finished chunk 464
Finished chunk 465
Finished chunk 466
Finished chunk 467
Finished chunk 468
Finished chunk 469
Finished chunk 470
Finished chunk 471
Finished chunk 472
Finished chunk 473
Finished chunk 474
Finished chunk 475
Finished chunk 476
Finished chunk 477
Finished chunk 478
Finished chunk 479
Finished chunk 480
Finished chunk 481
Finished chunk 482
Finished chunk 483
Finished chunk 484
Finished chunk 485
Finished chunk 486
Finished chunk 487
Finished chunk 488
Finished chunk 489
Finished chunk 490
Finished chunk 491
Finished chunk 492
Finished chunk 493
Finished chunk 494
Finished chunk 495
Finished chunk 496
Finished chunk 497
Finished chunk 498
Finished chunk 499
Finished chunk 500
Finished chunk 501
Finished chunk 502
Finished chunk 503
Finished chunk 504
Finished chunk 505
Finished chunk 506
Finished chunk 507
Finished chunk 508
Finished chunk 509
Finished chunk 510
Finished chunk 511
Finished chunk 512
Finished chunk 513
Finished chunk 514
Finished chunk 515
Finished chunk 516
Finished chunk 517
Finished chunk 518
Finished chunk 519
Finished chunk 520
Finished chunk 521
Finished chunk 522
Finished chunk 523
Finished chunk 524
Finished chunk 525
Finished chunk 526
Finished chunk 527
Finished chunk 528
Finished chunk 529
Finished chunk 530
Finished chunk 531
Finished chunk 532
Finished chunk 533
Finished chunk 534
Finished chunk 535
Finished chunk 536
Finished chunk 537
Finished chunk 538
Finished chunk 539
Finished chunk 540
Finished chunk 541
Finished chunk 542
Finished chunk 543
Finished chunk 544
Finished chunk 545
Finished chunk 546
Finished chunk 547
Finished chunk 548
Finished chunk 549
Finished chunk 550
Finished chunk 551
Finished chunk 552
Finished chunk 553
Finished chunk 554
Finished chunk 555
Finished chunk 556
Finished chunk 557
Finished chunk 558
Finished chunk 559
Finished chunk 560
Finished chunk 561
Finished chunk 562
Finished chunk 563
Finished chunk 564
Finished chunk 565
Finished chunk 566
Finished chunk 567
Finished chunk 568
Finished chunk 569
Finished chunk 570
Finished chunk 571
Finished chunk 572
Finished chunk 573
Finished chunk 574
Finished chunk 575
Finished chunk 576
Finished chunk 577
Finished chunk 578
Finished chunk 579
Finished chunk 580
Finished chunk 581
Finished chunk 582
Finished chunk 583
Finished chunk 584
Finished chunk 585
Finished chunk 586
Finished chunk 587
Finished chunk 588
Finished chunk 589
Finished chunk 590
Finished chunk 591
Finished chunk 592
Finished chunk 593
Finished chunk 594
Finished chunk 595
Finished chunk 596
Finished chunk 597
Finished chunk 598
Finished chunk 599
Finished chunk 600
Finished chunk 601
Finished chunk 602
Finished chunk 603
Finished chunk 604
Finished chunk 605
Finished chunk 606
Finished chunk 607
Finished chunk 608
Finished chunk 609
Finished chunk 610
Finished chunk 611
Finished chunk 612
Finished chunk 613
Finished chunk 614
Finished chunk 615
Finished chunk 616
Finished chunk 617
Finished chunk 618
Finished chunk 619
Finished chunk 620
Finished chunk 621
Finished chunk 622
Finished chunk 623
Finished chunk 624
Finished chunk 625
Finished chunk 626
Finished chunk 627
Finished chunk 628
Finished chunk 629
Finished chunk 630
Finished chunk 631
Finished chunk 632
Finished chunk 633
Finished chunk 634
Finished chunk 635
Finished chunk 636
Finished chunk 637
Finished chunk 638
Finished chunk 639
Finished chunk 640
Finished chunk 641
Finished chunk 642
Finished chunk 643
Finished chunk 644
Finished chunk 645
Finished chunk 646
Finished chunk 647
Finished chunk 648
Finished chunk 649
Finished chunk 650
Finished chunk 651
Finished chunk 652
Finished chunk 653
Finished chunk 654
Finished chunk 655
Finished chunk 656
Finished chunk 657
Finished chunk 658
Finished chunk 659
Finished chunk 660
Finished chunk 661
Finished chunk 662
Finished chunk 663
Finished chunk 664
Finished chunk 665
Finished chunk 666
Finished chunk 667
Finished chunk 668
Finished chunk 669
Finished chunk 670
Finished chunk 671
Finished chunk 672
Finished chunk 673
Finished chunk 674
Finished chunk 675
Finished chunk 676
Finished chunk 677
Finished chunk 678
Finished chunk 679
Finished chunk 680
Finished chunk 681
Finished chunk 682
Finished chunk 683
Finished chunk 684
Finished chunk 685
Finished chunk 686
Finished chunk 687
Finished chunk 688
Finished chunk 689
Finished chunk 690
Finished chunk 691
Finished chunk 692
Finished chunk 693
Finished chunk 694
Finished chunk 695
Finished chunk 696
Finished chunk 697
Finished chunk 698
Finished chunk 699
Finished chunk 700
Finished chunk 701
Finished chunk 702
Finished chunk 703
Finished chunk 704
Finished chunk 705
Finished chunk 706
Finished chunk 707
Finished chunk 708
Finished chunk 709
Finished chunk 710
Finished chunk 711
Finished chunk 712
Finished chunk 713
Finished chunk 714
Finished chunk 715
Finished chunk 716
Finished chunk 717
Finished chunk 718
Finished chunk 719
Finished chunk 720
Finished chunk 721
Finished chunk 722
Finished chunk 723
Finished chunk 724
Finished chunk 725
Finished chunk 726
Finished chunk 727
Finished chunk 728
Finished chunk 729
Finished chunk 730
Finished chunk 731
Finished chunk 732
Finished chunk 733
Finished chunk 734
Finished chunk 735
Finished chunk 736
Finished chunk 737
Finished chunk 738
Finished chunk 739
Finished chunk 740
Finished chunk 741
Finished chunk 742
Finished chunk 743
Finished chunk 744
Finished chunk 745
Finished chunk 746
Finished chunk 747
Finished chunk 748
Finished chunk 749
Finished chunk 750
Finished chunk 751
Finished chunk 752
Finished chunk 753
Finished chunk 754
Finished chunk 755
Finished chunk 756
Finished chunk 757
Finished chunk 758
Finished chunk 759
Finished chunk 760
Finished chunk 761
Finished chunk 762
Finished chunk 763
Finished chunk 764
Finished chunk 765
Finished chunk 766
Finished chunk 767
Finished chunk 768
Finished chunk 769
Finished chunk 770
Finished chunk 771
Finished chunk 772
Finished chunk 773
Finished chunk 774
Finished chunk 775
Finished chunk 776
Finished chunk 777
Finished chunk 778
Finished chunk 779
Finished chunk 780
Finished chunk 781
Finished chunk 782
Finished chunk 783
Finished chunk 784
Finished chunk 785
Finished chunk 786
Finished chunk 787
Finished chunk 788
Finished chunk 789
Finished chunk 790
Finished chunk 791
Finished chunk 792
Finished chunk 793
Finished chunk 794
Finished chunk 795
Finished chunk 796
Finished chunk 797
Finished chunk 798
Finished chunk 799
Finished chunk 800
Finished chunk 801
Finished chunk 802
Finished chunk 803
Finished chunk 804
Finished chunk 805
Finished chunk 806
Finished chunk 807
Finished chunk 808
Finished chunk 809
Finished chunk 810
Finished chunk 811
Finished chunk 812
Finished chunk 813
Finished chunk 814
Finished chunk 815
Finished chunk 816
Finished chunk 817
Finished chunk 818
Finished chunk 819
Finished chunk 820
Finished chunk 821
Finished chunk 822
Finished chunk 823
Finished chunk 824
Finished chunk 825
Finished chunk 826
Finished chunk 827
Finished chunk 828
Finished chunk 829
Finished chunk 830
Finished chunk 831
Finished chunk 832
Finished chunk 833
Finished chunk 834
Finished chunk 835
Finished chunk 836
Finished chunk 837
Finished chunk 838
Finished chunk 839
Finished chunk 840
Finished chunk 841
Finished chunk 842
Finished chunk 843
Finished chunk 844
Finished chunk 845
Finished chunk 846
Finished chunk 847
Finished chunk 848
Finished chunk 849
Finished chunk 850
Finished chunk 851
Finished chunk 852
Finished chunk 853
Finished chunk 854
Finished chunk 855
Finished chunk 856
Finished chunk 857
Finished chunk 858
Finished chunk 859
Finished chunk 860
Finished chunk 861
Finished chunk 862
Finished chunk 863
Finished chunk 864
Finished chunk 865
Finished chunk 866

In [ ]:
vitals = pd.concat(filtered_chunks, ignore_index=True)

print("Vitals shape:", vitals.shape)
vitals.head()

NameError: name 'pd' is not defined

In [ ]:
vitals = vitals[[
    "subject_id",
    "hadm_id",
    "stay_id",
    "charttime",
    "itemid",
    "valuenum",
    "valueuom"
]]

vitals["charttime"] = pd.to_datetime(vitals["charttime"])

vitals.head()

,subject_id,hadm_id,stay_id,charttime,itemid,valuenum,valueuom
0,10000032,29079034,39553978,2180-07-23 14:12:00,220045,91.0,bpm
1,10000032,29079034,39553978,2180-07-23 14:12:00,220210,24.0,insp/min
2,10000032,29079034,39553978,2180-07-23 14:13:00,220277,98.0,%
3,10000032,29079034,39553978,2180-07-23 14:30:00,220045,93.0,bpm
4,10000032,29079034,39553978,2180-07-23 14:30:00,220210,21.0,insp/min

In [ ]:
vitals.to_csv(output_dir / "vitals_filtered.csv", index=False)

print("Filtered vitals saved successfully")

Filtered vitals saved successfully

In [ ]:
vitals.shape

(35596303, 7)

In [ ]:
itemid_to_label = {
    220045: "heart_rate",
    220210: "resp_rate",
    223762: "temp_c",
    220277: "spo2",
    220050: "abp_sys",
    220051: "abp_dia",
    220052: "abp_mean"
}

vitals["feature_name"] = vitals["itemid"].map(itemid_to_label)
vitals.head()

,subject_id,hadm_id,stay_id,charttime,itemid,valuenum,valueuom,feature_name
0,10000032,29079034,39553978,2180-07-23 14:12:00,220045,91.0,bpm,heart_rate
1,10000032,29079034,39553978,2180-07-23 14:12:00,220210,24.0,insp/min,resp_rate
2,10000032,29079034,39553978,2180-07-23 14:13:00,220277,98.0,%,spo2
3,10000032,29079034,39553978,2180-07-23 14:30:00,220045,93.0,bpm,heart_rate
4,10000032,29079034,39553978,2180-07-23 14:30:00,220210,21.0,insp/min,resp_rate

In [ ]:
vitals["feature_name"].isnull().sum()

np.int64(0)

In [ ]:
vitals["charttime_hour"] = vitals["charttime"].dt.floor("h")
vitals.head()

,subject_id,hadm_id,stay_id,charttime,itemid,valuenum,valueuom,feature_name,charttime_hour
0,10000032,29079034,39553978,2180-07-23 14:12:00,220045,91.0,bpm,heart_rate,2180-07-23 14:00:00
1,10000032,29079034,39553978,2180-07-23 14:12:00,220210,24.0,insp/min,resp_rate,2180-07-23 14:00:00
2,10000032,29079034,39553978,2180-07-23 14:13:00,220277,98.0,%,spo2,2180-07-23 14:00:00
3,10000032,29079034,39553978,2180-07-23 14:30:00,220045,93.0,bpm,heart_rate,2180-07-23 14:00:00
4,10000032,29079034,39553978,2180-07-23 14:30:00,220210,21.0,insp/min,resp_rate,2180-07-23 14:00:00

In [ ]:
vitals_hourly = (
    vitals.groupby(["stay_id", "charttime_hour", "feature_name"])["valuenum"]
    .mean()
    .reset_index()
)

vitals_hourly.head()

NameError: name 'vitals' is not defined